version: '1.0'
services:
  server:
    image: klakegg/hugo:0.101.0-alpine
    # entrypoint: ["/bin/bash", "-c"]
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        ./notion-to-gh-pages.sh
        hugo server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    stdin_open: true
    tty: true